# Generated by Django 2.0.2 on 2018-02-19 14:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(max_length=64)),
                ('doctor_name', models.CharField(max_length=128)),
                ('patient_id', models.CharField(max_length=64)),
                ('patient_name', models.CharField(max_length=128)),
                ('diagnosis', models.CharField(choices=[('cholera', 'Cholera'), ('plague', 'Plague'), ('scarletfever', 'Scarlet fever'), ('cold', 'Common cold'), ('hypochondria', 'Hypochondria')], max_length=32)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
