# Generated by Django 2.0.2 on 2018-02-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_report_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='diagnosis',
            field=models.CharField(choices=[('cholera', 'Cholera'), ('scarletfever', 'Scarlet fever'), ('typhoid', 'Typhoid'), ('rubella', 'Rubella'), ('smallpox', 'Smallpox')], max_length=32),
        ),
    ]
